name: Purge Cloudflare Cache
description: "Purge Cloudflare Cache"
inputs:
  zone:
    description: "The Cloudflare Zone ID"
    required: true
  api-token:
    description: "The Cloudflare API Token with purge cache permission"
    required: true
  prefix:
    description: "The prefix to purge cache"
    required: true
runs:
  using: composite
  steps:
    - name: Purge Cloudflare Cache
      shell: bash
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ inputs.zone }}/purge_cache" \
          -H "Authorization: Bearer ${{ inputs.api-token }}" \
          -H "Content-Type: application/json" \
          --data '{"prefixes":["${{ inputs.prefix }}"]}'
