name: Cloudflare Pages

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir public
          echo "HELLO WORLD" > public/index.html
        shell: bash
    
      - name: Docs
        uses: ./.github/actions/cloudflare-upload
        with:
          upload-dir: public
          project-name: docs-content
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
