name: Render datasheets

on:
  workflow_dispatch:

jobs:
  render-datasheets:
    runs-on: ubuntu-latest
    env:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Render
        run: |
         cd scripts/datasheet-rendering
         ./render-datasheets.sh